# <!-- EXAMPLE CONTENT - EDIT / REPLACE BELOW -->
title: "{{< var website-title >}}"
subtitle: "A template"
author: "Jens Wiesehahn"
# institute: 

project:
    type: website

website:
    description: "{{< var website-description >}}"
    site-url: "{{< var website-url >}}"
    repo-url: "{{< var repository-url >}}"
    favicon: images/triangle_favicon.png


format: # format options: https://quarto.org/docs/reference/formats/presentations/revealjs.html
    revealjs:
        width: 1600
        height: 1200
        margin: 0.15
        #title-slide-attributes:
        #    data-background-image: images/triangle_logo.png
        #    data-background-size: cover
        #    data-background-opacity: "1"
        slide-number: c/t
        show-slide-number: speaker
        transition: slide
        background-transition: fade
        preview-links: false 
        preload-iframes: false 
        theme: [default, assets/custom_theme.scss]
        navigation-mode: vertical
        tbl-cap-location: bottom
        mainfont: Nunito
        monofont: Roboto Mono
        code-line-numbers: false
        code-fold: true
        code-summary: "Show the code"
        code-overflow: wrap
        code-copy: hover
        highlight-style: arrow
        logo: images/triangle_logo.png
        toc-depth: 2
        quarto-required: ">= 1.3"
        controls-layout: bottom-right
        history: false
        #footer: 
        #execute:
        #    eval: false

revealjs-plugins:
    - verticator
    - attribution

filters:
    - lightbox

bibliography: references.bib


include-after-body: assets/logo-hyperlink.html